name: CI

on:
  push:
    branches: [development, codebase_improvements]
    paths:
      - 'src/**'
      - 'prisma/**'
      - 'package.json'
      - 'package-lock.json'
      - 'postcss.config.*'
      - 'next.config.*'
      - 'tailwind.config.*'
      - 'tsconfig.json'
      - 'eslint.config.*'
      - 'components.json'
  pull_request:
    branches: [main, development]
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Cache node modules and Next.js build cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.npm
            .next/cache
          key: ${{ runner.os }}-node-${{ hashFiles('package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Install dependencies
        run: npm ci

      - name: Lint code
        run: npm run lint

      - name: Type check
        run: npm run typecheck
        continue-on-error: true # Remove this if you want to fail on type errors

      - name: Prisma generate
        run: npx prisma generate

      - name: Prisma migrate status
        run: npx prisma migrate status

      - name: Build app
        run: npm run build

      - name: Seed database (create admin user)
        run: npm run prisma:seed

      # Uncomment if you have tests
      # - name: Run tests
      #   run: npm test 